interface IStatus {
  selected?: string,
  selectedchild?: string,
  ipTypeSuperiorNumbers?: string,
  ipLocation?: string,
  countryType?: string,
  ipTypeNumber?: string,
  ipFormNumber?: string,
  benginShowDate?: string,
  endShowDate?: string,
  ipStatus?: string,
  ipSex?: string,
  currentPage?: number,
  pageSize?: number,
  ipIsAuthenticated?: number,
}
